CREATE TABLE `bond_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`detaineeName` varchar(255) NOT NULL,
	`aNumber` varchar(20),
	`dateOfBirth` varchar(20),
	`countryOfBirth` varchar(100),
	`dateOfEntry` varchar(20),
	`mannerOfEntry` varchar(100),
	`detentionCenter` varchar(255),
	`dateDetained` varchar(20),
	`hasAggravatedFelony` boolean DEFAULT false,
	`hasDrugCrimes` boolean DEFAULT false,
	`detainedAtPortOfEntry` boolean DEFAULT false,
	`hasPriorDeportation` boolean DEFAULT false,
	`hasFinalRemovalOrder` boolean DEFAULT false,
	`criminalHistory` text,
	`rehabilitationEvidence` text,
	`hasCharacterLetters` boolean DEFAULT false,
	`characterLettersCount` int DEFAULT 0,
	`familyTiesInUS` text,
	`usResidenceLength` varchar(50),
	`hasFixedAddress` boolean DEFAULT false,
	`currentAddress` text,
	`employmentHistory` text,
	`currentEmployer` varchar(255),
	`hasPropertyInUS` boolean DEFAULT false,
	`propertyDetails` text,
	`previousDeportations` text,
	`pendingApplications` text,
	`eligibleForRelief` boolean DEFAULT false,
	`reliefType` varchar(255),
	`medicalConditions` text,
	`specialCircumstances` text,
	`sponsorName` varchar(255),
	`sponsorRelation` varchar(100),
	`sponsorStatus` varchar(100),
	`sponsorIncome` varchar(50),
	`sponsorPhone` varchar(30),
	`sponsorEmail` varchar(320),
	`sponsorUnderstandsRisk` boolean DEFAULT false,
	`contactPhone` varchar(30),
	`contactEmail` varchar(320),
	`preferredLanguage` varchar(10) DEFAULT 'en',
	`status` enum('new','reviewed','in_progress','completed','archived') NOT NULL DEFAULT 'new',
	`notes` text,
	`assignedTo` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bond_submissions_id` PRIMARY KEY(`id`)
);
