CREATE TABLE `emergency_plan_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`planId` int NOT NULL,
	`userId` int NOT NULL,
	`documentType` enum('passport','birth_certificate','social_security_card','green_card','work_permit','visa','marriage_certificate','divorce_decree','power_of_attorney','medical_records','school_records','financial_records','property_deed','vehicle_title','insurance_policy','other') NOT NULL,
	`documentName` varchar(255) NOT NULL,
	`description` text,
	`fileKey` varchar(500) NOT NULL,
	`fileUrl` varchar(1000) NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileSize` int NOT NULL,
	`mimeType` varchar(100) NOT NULL,
	`belongsTo` varchar(255),
	`uploadedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `emergency_plan_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `emergency_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`planName` varchar(255) NOT NULL DEFAULT 'My Family Emergency Plan',
	`ownerName` varchar(255) NOT NULL,
	`ownerPhone` varchar(30),
	`ownerEmail` varchar(320),
	`ownerAddress` text,
	`emergencyContacts` text,
	`attorneyName` varchar(255),
	`attorneyPhone` varchar(30),
	`attorneyEmail` varchar(320),
	`attorneyFirm` varchar(255),
	`consulateName` varchar(255),
	`consulatePhone` varchar(30),
	`consulateAddress` text,
	`children` text,
	`poaDesignee` varchar(255),
	`poaDesigneePhone` varchar(30),
	`poaDesigneeRelationship` varchar(100),
	`hasPOADocument` boolean DEFAULT false,
	`documentLocations` text,
	`bankName` varchar(255),
	`bankAccountInfo` text,
	`financialPOA` varchar(255),
	`specialInstructions` text,
	`knowYourRightsAcknowledged` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `emergency_plans_id` PRIMARY KEY(`id`)
);
