CREATE TABLE `character_reference_letters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accessToken` varchar(64) NOT NULL,
	`caseId` varchar(50),
	`respondentName` varchar(255) NOT NULL,
	`caseType` enum('bond_hearing','asylum','cancellation_of_removal','adjustment_of_status','naturalization','waiver','other') NOT NULL DEFAULT 'bond_hearing',
	`writerName` varchar(255),
	`writerRelationship` varchar(100),
	`writerAddress` text,
	`writerCity` varchar(100),
	`writerState` varchar(50),
	`writerZip` varchar(20),
	`writerPhone` varchar(30),
	`writerEmail` varchar(320),
	`writerOccupation` varchar(100),
	`writerEmployer` varchar(255),
	`writerImmigrationStatus` varchar(100),
	`howLongKnown` varchar(50),
	`howMet` text,
	`frequencyOfContact` varchar(100),
	`characterDescription` text,
	`specificExamples` text,
	`communityInvolvement` text,
	`familyRole` text,
	`workEthic` text,
	`moralCharacter` text,
	`whyDeservesBond` text,
	`additionalComments` text,
	`signatureData` text,
	`signedAt` timestamp,
	`signedIpAddress` varchar(45),
	`pdfFileKey` varchar(500),
	`pdfFileUrl` varchar(1000),
	`status` enum('pending','draft','completed','submitted') NOT NULL DEFAULT 'pending',
	`requestedBy` int,
	`requestedAt` timestamp NOT NULL DEFAULT (now()),
	`language` varchar(10) DEFAULT 'en',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `character_reference_letters_id` PRIMARY KEY(`id`),
	CONSTRAINT `character_reference_letters_accessToken_unique` UNIQUE(`accessToken`)
);
