CREATE TABLE `sponsor_letters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`respondentName` varchar(255) NOT NULL,
	`respondentRelationship` varchar(100) NOT NULL,
	`respondentANumber` varchar(20),
	`sponsorName` varchar(255) NOT NULL,
	`sponsorAddress` varchar(500) NOT NULL,
	`sponsorCity` varchar(100) NOT NULL,
	`sponsorState` varchar(50) NOT NULL,
	`sponsorZip` varchar(20) NOT NULL,
	`sponsorPhone` varchar(30) NOT NULL,
	`sponsorEmail` varchar(320),
	`sponsorDateOfBirth` varchar(20),
	`sponsorOccupation` varchar(100),
	`sponsorEmployer` varchar(255),
	`sponsorEmployerAddress` varchar(500),
	`sponsorImmigrationStatus` varchar(100) NOT NULL,
	`sponsorAnnualIncome` varchar(50),
	`sponsorEmploymentLength` varchar(50),
	`householdSize` int,
	`housingType` varchar(50),
	`housingAddress` varchar(500),
	`bedroomCount` int,
	`willProvideHousing` boolean DEFAULT true,
	`willEnsureCourtAppearance` boolean DEFAULT true,
	`willProvideTransportation` boolean DEFAULT false,
	`willProvideFinancialSupport` boolean DEFAULT false,
	`additionalCommitments` text,
	`howLongKnown` varchar(50),
	`relationshipDescription` text,
	`whyWillingToSponsor` text,
	`characterStatement` text,
	`flightRiskStatement` text,
	`signatureData` text,
	`signedAt` timestamp,
	`signedIpAddress` varchar(45),
	`pdfFileKey` varchar(500),
	`pdfFileUrl` varchar(1000),
	`language` varchar(10) DEFAULT 'en',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sponsor_letters_id` PRIMARY KEY(`id`)
);
