import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'es' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.attorneys": "Attorneys",
    "nav.practice_areas": "Practice Areas",
    "nav.knowledge_center": "Knowledge Center",
    "nav.contact": "Contact",
    "nav.request_consultation": "Request Consultation",
    
    // Hero
    "hero.call_now": "Call Now",
    "hero.title_prefix": "Experts in",
    "hero.title_suffix": "Removal Defense",
    "hero.description": "When you or a loved one faces immigration detention, time is critical. Our experienced attorneys provide compassionate, aggressive representation to protect your rights and secure your freedom.",
    "hero.meet_attorneys": "Bond Questionnaire",
    
    // Footer
    "footer.tagline": "Providing authoritative legal representation with a commitment to justice and integrity since 1985.",
    "footer.practice_areas": "Practice Areas",
    "footer.contact": "Contact",
    "footer.newsletter": "Newsletter",
    "footer.subscribe_text": "Subscribe for legal insights and firm updates.",
    "footer.email_placeholder": "Email address",
    "footer.join": "Join",
    "footer.rights": "Amaral Law Firm. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.disclaimer": "Disclaimer",
    "footer.accessibility": "Accessibility",
    "footer.admin": "Admin Portal",

    // Home Content
    "home.excellence_title": "Decades of Excellence in Legal Practice",
    "home.excellence_p1": "At Amaral Law, we specialize exclusively in defending immigrants facing deportation. We understand that your life in the United States is on the line, and we fight tirelessly to keep families together.",
    "home.excellence_p2": "With a proven track record in immigration court, our attorneys have successfully defended the rights of countless individuals against removal proceedings.",
    "home.learn_more": "Learn More About Our Firm",
    "home.practice_areas_title": "Our Practice Areas",
    "home.practice_areas_desc": "We focus 100% on removal defense. Our specialized expertise ensures you have the strongest possible advocate in immigration court.",
    "home.latest_insights": "Latest Legal Insights",
    "home.view_all_articles": "View All Articles",

    // Practice Areas
    "practice.removal_defense": "Removal Defense",
    "practice.removal_defense_desc": "Aggressive representation in immigration court to stop deportation proceedings.",
    "practice.asylum": "Asylum & Appeals",
    "practice.asylum_desc": "Expert handling of asylum claims and BIA appeals for complex cases.",
    "practice.family": "Family Petitions",
    "practice.family_desc": "Reuniting families through status adjustment and consular processing.",
    "practice.bond": "Bond Hearings",
    "practice.bond_desc": "Fighting for your release from immigration detention centers.",
    "practice.crimmigration": "Crimmigration",
    "practice.crimmigration_desc": "Defending non-citizens facing criminal charges that impact immigration status.",
    "practice.federal": "Federal Litigation",
    "practice.federal_desc": "Challenging delayed or denied applications in federal court.",

    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "Get in touch with our legal team for a consultation.",
    "contact.form_title": "Send us a message",
    "contact.name": "Full Name",
    "contact.email": "Email Address",
    "contact.phone": "Phone Number",
    "contact.message": "Message",
    "contact.submit": "Send Message",
    "contact.info_title": "Contact Information",
    "contact.address": "Address",
    "contact.hours": "Business Hours",
    "contact.hours_val": "Mon-Fri: 9:00 AM - 6:00 PM",

    // Bond Questionnaire
    "bond.title": "Bond Questionnaire",
    "bond.subtitle": "Please complete this form to help us assess your eligibility for an immigration bond.",
    "bond.detainee_info": "Detainee Information",
    "bond.full_name": "Detainee's Full Name",
    "bond.a_number": "Alien Registration Number (A-Number)",
    "bond.dob": "Date of Birth",
    "bond.country_birth": "Country of Birth",
    "bond.date_entry": "Date of Entry to U.S.",
    "bond.manner_entry": "Manner of Entry (e.g. Visa, Border)",
    "bond.detention_info": "Detention Information",
    "bond.detention_center": "Current Detention Center",
    "bond.date_detained": "Date Detained",
    "bond.criminal_history": "Criminal History (if any)",
    "bond.family_ties": "Family Ties in U.S.",
    "bond.sponsor_info": "Sponsor Information",
    "bond.sponsor_name": "Sponsor Name",
    "bond.sponsor_relation": "Relation to Detainee",
    "bond.sponsor_status": "Sponsor Immigration Status",
    "bond.sponsor_income": "Annual Income",
    "bond.submit": "Submit Questionnaire",

    // Vanity Number Section
    "vanity.title": "Memorize This Number: 1-844-ICE-FREE",
    "vanity.subtitle": "Immediate Legal Assistance When You Need It Most",
    "vanity.description": "In the event of an unexpected detention by ICE, every second counts. Memorizing 1-844-ICE-FREE (1-844-262-5442) ensures you or your loved ones can instantly connect with our removal defense team. We are available to provide urgent guidance and representation to fight for your release.",
    "vanity.cta": "Save Contact Now",

    // Attorneys Page
    "attorneys.title": "Our Legal Team",
    "attorneys.subtitle": "Experienced attorneys dedicated to your case",
    "attorneys.ana.role": "Lead Immigration Attorney",
    "attorneys.ana.bio": "An immigrant from Brazil with over 40 years in the U.S., Ana Paola specializes in detention defense and removal proceedings, bringing personal experience and deep empathy to every case.",
    "attorneys.reggie.role": "Complex Immigration Litigation Attorney",
    "attorneys.reggie.bio": "Specialized in complex immigration litigation with extensive experience in appellate proceedings, federal court litigation, and challenging immigration cases requiring advanced legal strategies.",
    "attorneys.balaiz.role": "Of Counsel - Civil Litigation",
    "attorneys.balaiz.bio": "Experienced in civil litigation matters including contract disputes, property claims, and complex civil cases. Provides expert legal representation for clients needing specialized civil law counsel.",
    "attorneys.values.title": "Our Values",
    "attorneys.values.justice": "Justice for All",
    "attorneys.values.justice_desc": "We believe every person deserves quality legal representation, regardless of their circumstances.",
    "attorneys.values.compassion": "Compassionate Advocacy",
    "attorneys.values.compassion_desc": "We treat each client with dignity, respect, and genuine understanding of their situation.",
    "attorneys.values.excellence": "Legal Excellence",
    "attorneys.values.excellence_desc": "We maintain the highest standards of legal practice and tirelessly pursue the best outcomes.",
    "attorneys.values.community": "Community Commitment",
    "attorneys.values.community_desc": "We actively serve immigrant communities and advocate for fair immigration reform.",
    "attorneys.cta.title": "Don't Face Immigration Detention Alone",
    "attorneys.cta.desc": "Every day in detention matters. Contact us today for a free consultation and learn how we can help secure your release and fight for your rights.",
    "attorneys.cta.button": "Request Free Consultation",

    // Knowledge Center
    "knowledge.title": "Knowledge Center",
    "knowledge.subtitle": "Expert legal insights, in-depth guides, and practical resources to help you navigate complex legal landscapes.",
    "knowledge.tab.guides": "Legal Guides",
    "knowledge.tab.resources": "Downloadable Resources",
    "knowledge.search": "Search topics...",
    "knowledge.read_article": "Read Article",
    "knowledge.no_results": "No guides found matching your search.",
    "knowledge.newsletter.title": "Stay Informed",
    "knowledge.newsletter.desc": "Subscribe to our monthly newsletter for the latest legal insights, firm news, and regulatory updates delivered directly to your inbox.",
    "knowledge.newsletter.placeholder": "Enter your email address",
    "knowledge.newsletter.button": "Subscribe",
    "knowledge.newsletter.disclaimer": "By subscribing, you agree to our Privacy Policy. You can unsubscribe at any time.",
    
    // Guides
    "guide.1.title": "Corporate Liability in the Digital Age",
    "guide.1.desc": "A comprehensive guide to understanding new liability risks for digital-first companies.",
    "guide.2.title": "Estate Planning for Business Owners",
    "guide.2.desc": "Strategies to protect your business assets and ensure a smooth succession.",
    "guide.3.title": "Intellectual Property: Patent vs. Trade Secret",
    "guide.3.desc": "Deciding which protection mechanism is right for your innovation.",
    "guide.4.title": "Navigating Commercial Lease Disputes",
    "guide.4.desc": "Key steps to take when facing a dispute with your commercial landlord or tenant.",
    "guide.5.title": "The 2026 Tax Reform: What You Need to Know",
    "guide.5.desc": "An early look at proposed changes to the tax code and how to prepare.",
    "guide.6.title": "Family Law: Prenuptial Agreements Explained",
    "guide.6.desc": "Dispelling common myths about prenups and understanding their benefits.",
    
    // Resources
    "resource.1.title": "2025 Corporate Compliance Checklist",
    "resource.2.title": "Estate Planning Questionnaire",
    "resource.3.title": "Intellectual Property Audit Template",
    "resource.4.title": "Commercial Lease Terminology Glossary",

    // Home Insights
    "home.insight.1.title": "Understanding Your Rights in Immigration Court",
    "home.insight.1.cat": "Removal Defense",
    "home.insight.2.title": "How to Post Bond for a Detained Relative",
    "home.insight.2.cat": "Detention",
    "home.insight.3.title": "Changes to Asylum Eligibility in 2024",
    "home.insight.3.cat": "Asylum",
    "home.insight.desc": "Read our expert analysis on this critical topic affecting businesses and individuals alike.",

    // Bond Questionnaire Extras
    "bond.description": "Please provide accurate details about the person currently detained.",
    "bond.placeholder.name": "e.g. Juan Perez",
    "bond.placeholder.a_number": "A-123-456-789",
    "bond.placeholder.country": "e.g. Brazil",
    "bond.placeholder.manner": "e.g. Visa, Border Crossing",
    "bond.placeholder.center": "e.g. Krome Detention Center",
    "bond.placeholder.criminal": "Please list any arrests or convictions...",
    "bond.placeholder.family": "List family members currently in the U.S. (Relationship and Status)",
    "bond.placeholder.sponsor_name": "e.g. Maria Perez",
    "bond.placeholder.sponsor_relation": "e.g. Wife",
    "bond.placeholder.sponsor_status": "e.g. U.S. Citizen, Green Card Holder",
    "bond.placeholder.sponsor_income": "e.g. $45,000",

    // Consultation Extras
    "consultation.title": "Request a Consultation",
    "consultation.subtitle": "Take the first step towards resolving your legal matter. Fill out the form below, and our team will review your case.",
    "consultation.step1": "Case Details",
    "consultation.step2": "Personal Info",
    "consultation.step3": "Scheduling",
    "consultation.step1_title": "Tell Us About Your Case",
    "consultation.step2_title": "Your Contact Information",
    "consultation.step3_title": "Preferred Schedule",
    "consultation.confidentiality": "All information provided is strictly confidential and protected by attorney-client privilege.",
    "consultation.label.area": "Practice Area",
    "consultation.placeholder.area": "Select a practice area",
    "consultation.option.other": "Other Legal Matter",
    "consultation.label.description": "Brief Description of Your Situation",
    "consultation.placeholder.description": "Please describe your legal issue, including any important dates or deadlines...",
    "consultation.label.urgency": "Urgency Level",
    "consultation.urgency.low": "Low - Planning ahead",
    "consultation.urgency.medium": "Medium - Need advice soon",
    "consultation.urgency.high": "High - Immediate action required",
    "consultation.button.next": "Next Step",
    "consultation.button.back": "Back",
    "consultation.button.submit": "Submit Request",
    "consultation.button.home": "Return to Home",
    "consultation.label.firstname": "First Name",
    "consultation.label.lastname": "Last Name",
    "consultation.label.email": "Email Address",
    "consultation.label.phone": "Phone Number",
    "consultation.label.preferred_contact": "Preferred Contact Method",
    "consultation.option.email": "Email",
    "consultation.option.phone": "Phone Call",
    "consultation.summary.title": "Review Your Information",
    "consultation.label.name": "Name",
    "consultation.label.contact": "Contact",
    "consultation.label.time": "Preferred Time of Day",
    "consultation.option.morning": "Morning (9AM - 12PM)",
    "consultation.option.afternoon": "Afternoon (12PM - 5PM)",
    "consultation.option.evening": "Evening (5PM - 7PM)",
    "consultation.consent": "I understand that submitting this form does not create an attorney-client relationship until a fee agreement is signed.",
    "consultation.success.title": "Request Received",
    "consultation.success.desc": "Thank you for contacting Amaral Law. Our team will review your information and contact you within 24 hours to confirm your consultation.",

    // Detention Page
    "detention.title": "Detention Response Guide",
    "detention.subtitle": "Immediate steps to take if a loved one has been detained by ICE.",
    "detention.step1.title": "Step 1: Locate the Detainee",
    "detention.step1.desc": "Use the ICE Detainee Locator to find where your loved one is being held. You will need their A-Number and country of birth, or their full name and date of birth.",
    "detention.step1.button": "ICE Locator",
    "detention.step2.title": "Step 2: Do Not Sign Anything",
    "detention.step2.desc": "Advise your loved one NOT to sign any documents without speaking to an attorney. Signing a 'voluntary departure' means they agree to be deported immediately.",
    "detention.step3.title": "Step 3: Contact an Attorney",
    "detention.step3.desc": "Call Amaral Law immediately at 1-844-ICE-FREE. We can intervene to stop transfer, request a bond hearing, and fight for their release.",
    "detention.step3.button": "Call Now",
    "detention.rights.title": "Know Your Rights",
    "detention.rights.point1": "You have the right to remain silent.",
    "detention.rights.point2": "You have the right to speak to a lawyer.",
    "detention.rights.point3": "You do not have to sign anything.",
    "detention.donts.title": "DO NOT",
    "detention.donts.point1": "Sign documents without legal advice",
    "detention.donts.point2": "Promise to pay a bond you cannot afford",
    "detention.donts.point3": "Discuss the case with anyone but your lawyer",
    "detention.donts.point4": "Miss court dates",
    "detention.donts.point5": "Ignore official notices",
    "detention.cta.title": "Don't Wait - Call Now",
    "detention.cta.button": "Contact Us Immediately",
    
    // Action Bar
    "action_bar.title": "Immediate Actions",
    "action_bar.ice_locator": "Locate Detainee (ICE)",
    "action_bar.eoir_status": "Check Case Status (EOIR)",

    // Consultation Scheduling
    "consultation.tab.inquiry": "Send Inquiry",
    "consultation.tab.booking": "Book Appointment",
    "consultation.booking.title": "Schedule Your Consultation",
    "consultation.booking.subtitle": "Select a time that works for you to speak with our attorneys.",
    "consultation.fee.title": "Consultation Fee: $250.00",
    "consultation.fee.desc": "Please note that there is a consultation fee of $250.00 for all initial appointments.",
    "consultation.fee.invoice": "A LawPay invoice will be sent to you via email prior to your appointment."
  },
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.attorneys": "Abogados",
    "nav.practice_areas": "Áreas de Práctica",
    "nav.knowledge_center": "Centro de Conocimiento",
    "nav.contact": "Contacto",
    "nav.request_consultation": "Solicitar Consulta",
    
    // Hero
    "hero.call_now": "Llamar Ahora",
    "hero.title_prefix": "Expertos en",
    "hero.title_suffix": "Defensa de Deportación",
    "hero.description": "Cuando usted o un ser querido enfrenta la detención de inmigración, el tiempo es crítico. Nuestros abogados experimentados brindan una representación compasiva y agresiva para proteger sus derechos y asegurar su libertad.",
    "hero.meet_attorneys": "Cuestionario de Fianza",
    
    // Footer
    "footer.tagline": "Brindando representación legal autorizada con un compromiso con la justicia y la integridad desde 1985.",
    "footer.practice_areas": "Áreas de Práctica",
    "footer.contact": "Contacto",
    "footer.newsletter": "Boletín",
    "footer.subscribe_text": "Suscríbase para recibir información legal y actualizaciones de la firma.",
    "footer.email_placeholder": "Dirección de correo electrónico",
    "footer.join": "Unirse",
    "footer.rights": "Amaral Law Firm. Todos los derechos reservados.",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
    "footer.disclaimer": "Aviso Legal",
    "footer.accessibility": "Accesibilidad",
    "footer.admin": "Portal de Administración",

    // Home Content
    "home.excellence_title": "Décadas de Excelencia en Práctica Legal",
    "home.excellence_p1": "En Amaral Law, nos especializamos exclusivamente en defender a inmigrantes que enfrentan la deportación. Entendemos que su vida en los Estados Unidos está en juego y luchamos incansablemente para mantener unidas a las familias.",
    "home.excellence_p2": "Con un historial comprobado en la corte de inmigración, nuestros abogados han defendido con éxito los derechos de innumerables personas contra los procedimientos de deportación.",
    "home.learn_more": "Más Sobre Nuestra Firma",
    "home.practice_areas_title": "Nuestras Áreas de Práctica",
    "home.practice_areas_desc": "Nos enfocamos 100% en la defensa contra la deportación. Nuestra experiencia especializada garantiza que tenga el defensor más fuerte posible en la corte de inmigración.",
    "home.latest_insights": "Últimas Perspectivas Legales",
    "home.view_all_articles": "Ver Todos los Artículos",

    // Practice Areas
    "practice.removal_defense": "Defensa de Deportación",
    "practice.removal_defense_desc": "Representación agresiva en la corte de inmigración para detener los procedimientos de deportación.",
    "practice.asylum": "Asilo y Apelaciones",
    "practice.asylum_desc": "Manejo experto de reclamos de asilo y apelaciones ante la BIA para casos complejos.",
    "practice.family": "Peticiones Familiares",
    "practice.family_desc": "Reuniendo familias a través del ajuste de estatus y el procesamiento consular.",
    "practice.bond": "Audiencias de Fianza",
    "practice.bond_desc": "Luchando por su liberación de los centros de detención de inmigración.",
    "practice.crimmigration": "Crimigración",
    "practice.crimmigration_desc": "Defendiendo a no ciudadanos que enfrentan cargos criminales que afectan su estatus migratorio.",
    "practice.federal": "Litigio Federal",
    "practice.federal_desc": "Desafiando solicitudes retrasadas o denegadas en la corte federal.",

    // Contact Page
    "contact.title": "Contáctenos",
    "contact.subtitle": "Póngase en contacto con nuestro equipo legal para una consulta.",
    "contact.form_title": "Envíenos un mensaje",
    "contact.name": "Nombre Completo",
    "contact.email": "Dirección de Correo",
    "contact.phone": "Número de Teléfono",
    "contact.message": "Mensaje",
    "contact.submit": "Enviar Mensaje",
    "contact.info_title": "Información de Contacto",
    "contact.address": "Dirección",
    "contact.hours": "Horario de Atención",
    "contact.hours_val": "Lun-Vie: 9:00 AM - 6:00 PM",

    // Bond Questionnaire
    "bond.title": "Cuestionario de Fianza",
    "bond.subtitle": "Por favor complete este formulario para ayudarnos a evaluar su elegibilidad para una fianza de inmigración.",
    "bond.detainee_info": "Información del Detenido",
    "bond.full_name": "Nombre Completo del Detenido",
    "bond.a_number": "Número de Registro de Extranjero (Número A)",
    "bond.dob": "Fecha de Nacimiento",
    "bond.country_birth": "País de Nacimiento",
    "bond.date_entry": "Fecha de Entrada a EE.UU.",
    "bond.manner_entry": "Forma de Entrada (ej. Visa, Frontera)",
    "bond.detention_info": "Información de Detención",
    "bond.detention_center": "Centro de Detención Actual",
    "bond.date_detained": "Fecha de Detención",
    "bond.criminal_history": "Historial Criminal (si lo hay)",
    "bond.family_ties": "Lazos Familiares en EE.UU.",
    "bond.sponsor_info": "Información del Patrocinador",
    "bond.sponsor_name": "Nombre del Patrocinador",
    "bond.sponsor_relation": "Relación con el Detenido",
    "bond.sponsor_status": "Estatus Migratorio del Patrocinador",
    "bond.sponsor_income": "Ingreso Anual",
    "bond.submit": "Enviar Cuestionario",

    // Vanity Number Section
    "vanity.title": "Memorice Este Número: 1-844-ICE-FREE",
    "vanity.subtitle": "Asistencia Legal Inmediata Cuando Más la Necesita",
    "vanity.description": "En caso de una detención inesperada por ICE, cada segundo cuenta. Memorizar 1-844-ICE-FREE (1-844-262-5442) asegura que usted o sus seres queridos puedan conectarse instantáneamente con nuestro equipo de defensa de deportación. Estamos disponibles para brindar orientación urgente y representación para luchar por su liberación.",
    "vanity.cta": "Guardar Contacto Ahora",

    // Attorneys Page
    "attorneys.title": "Nuestro Equipo Legal",
    "attorneys.subtitle": "Abogados experimentados dedicados a su caso",
    "attorneys.ana.role": "Abogada Principal de Inmigración",
    "attorneys.ana.bio": "Inmigrante de Brasil con más de 40 años en los EE. UU., Ana Paola se especializa en defensa de detención y procedimientos de deportación, aportando experiencia personal y profunda empatía a cada caso.",
    "attorneys.reggie.role": "Abogado de Litigios de Inmigración Complejos",
    "attorneys.reggie.bio": "Especializado en litigios de inmigración complejos con amplia experiencia en procedimientos de apelación, litigios en tribunales federales y casos de inmigración desafiantes que requieren estrategias legales avanzadas.",
    "attorneys.balaiz.role": "Of Counsel - Litigio Civil",
    "attorneys.balaiz.bio": "Experimentado en asuntos de litigio civil, incluidas disputas contractuales, reclamos de propiedad y casos civiles complejos. Brinda representación legal experta para clientes que necesitan asesoramiento especializado en derecho civil.",
    "attorneys.values.title": "Nuestros Valores",
    "attorneys.values.justice": "Justicia para Todos",
    "attorneys.values.justice_desc": "Creemos que cada persona merece una representación legal de calidad, independientemente de sus circunstancias.",
    "attorneys.values.compassion": "Defensa Compasiva",
    "attorneys.values.compassion_desc": "Tratamos a cada cliente con dignidad, respeto y una comprensión genuina de su situación.",
    "attorneys.values.excellence": "Excelencia Legal",
    "attorneys.values.excellence_desc": "Mantenemos los más altos estándares de práctica legal y perseguimos incansablemente los mejores resultados.",
    "attorneys.values.community": "Compromiso Comunitario",
    "attorneys.values.community_desc": "Servimos activamente a las comunidades de inmigrantes y abogamos por una reforma migratoria justa.",
    "attorneys.cta.title": "No Enfrente la Detención de Inmigración Solo",
    "attorneys.cta.desc": "Cada día en detención importa. Contáctenos hoy para una consulta gratuita y sepa cómo podemos ayudar a asegurar su liberación y luchar por sus derechos.",
    "attorneys.cta.button": "Solicitar Consulta Gratuita",

    // Knowledge Center
    "knowledge.title": "Centro de Conocimiento",
    "knowledge.subtitle": "Perspectivas legales expertas, guías detalladas y recursos prácticos para ayudarlo a navegar paisajes legales complejos.",
    "knowledge.tab.guides": "Guías Legales",
    "knowledge.tab.resources": "Recursos Descargables",
    "knowledge.search": "Buscar temas...",
    "knowledge.read_article": "Leer Artículo",
    "knowledge.no_results": "No se encontraron guías que coincidan con su búsqueda.",
    "knowledge.newsletter.title": "Manténgase Informado",
    "knowledge.newsletter.desc": "Suscríbase a nuestro boletín mensual para recibir las últimas perspectivas legales, noticias de la firma y actualizaciones regulatorias directamente en su bandeja de entrada.",
    "knowledge.newsletter.placeholder": "Ingrese su dirección de correo electrónico",
    "knowledge.newsletter.button": "Suscribirse",
    "knowledge.newsletter.disclaimer": "Al suscribirse, acepta nuestra Política de Privacidad. Puede darse de baja en cualquier momento.",
    
    // Guides
    "guide.1.title": "Responsabilidad Corporativa en la Era Digital",
    "guide.1.desc": "Una guía completa para comprender los nuevos riesgos de responsabilidad para las empresas digitales.",
    "guide.2.title": "Planificación Patrimonial para Dueños de Negocios",
    "guide.2.desc": "Estrategias para proteger los activos de su negocio y asegurar una sucesión sin problemas.",
    "guide.3.title": "Propiedad Intelectual: Patente vs. Secreto Comercial",
    "guide.3.desc": "Decidir qué mecanismo de protección es el adecuado para su innovación.",
    "guide.4.title": "Navegando Disputas de Arrendamiento Comercial",
    "guide.4.desc": "Pasos clave a seguir al enfrentar una disputa con su arrendador o inquilino comercial.",
    "guide.5.title": "La Reforma Fiscal de 2026: Lo Que Necesita Saber",
    "guide.5.desc": "Un primer vistazo a los cambios propuestos al código fiscal y cómo prepararse.",
    "guide.6.title": "Derecho de Familia: Acuerdos Prenupciales Explicados",
    "guide.6.desc": "Disipando mitos comunes sobre los acuerdos prenupciales y comprendiendo sus beneficios.",
    
    // Resources
    "resource.1.title": "Lista de Verificación de Cumplimiento Corporativo 2025",
    "resource.2.title": "Cuestionario de Planificación Patrimonial",
    "resource.3.title": "Plantilla de Auditoría de Propiedad Intelectual",
    "resource.4.title": "Glosario de Terminología de Arrendamiento Comercial",

    // Home Insights
    "home.insight.1.title": "Entendiendo Sus Derechos en la Corte de Inmigración",
    "home.insight.1.cat": "Defensa de Deportación",
    "home.insight.2.title": "Cómo Pagar una Fianza para un Pariente Detenido",
    "home.insight.2.cat": "Detención",
    "home.insight.3.title": "Cambios en la Elegibilidad de Asilo en 2024",
    "home.insight.3.cat": "Asilo",
    "home.insight.desc": "Lea nuestro análisis experto sobre este tema crítico que afecta a empresas e individuos por igual.",

    // Bond Questionnaire Extras
    "bond.description": "Por favor proporcione detalles precisos sobre la persona actualmente detenida.",
    "bond.placeholder.name": "ej. Juan Pérez",
    "bond.placeholder.a_number": "A-123-456-789",
    "bond.placeholder.country": "ej. México",
    "bond.placeholder.manner": "ej. Visa, Cruce Fronterizo",
    "bond.placeholder.center": "ej. Centro de Detención Krome",
    "bond.placeholder.criminal": "Por favor enumere cualquier arresto o condena...",
    "bond.placeholder.family": "Enumere los miembros de la familia actualmente en EE.UU. (Relación y Estatus)",
    "bond.placeholder.sponsor_name": "ej. María Pérez",
    "bond.placeholder.sponsor_relation": "ej. Esposa",
    "bond.placeholder.sponsor_status": "ej. Ciudadano de EE.UU., Residente Permanente",
    "bond.placeholder.sponsor_income": "ej. $45,000",

    // Consultation Extras
    "consultation.title": "Solicitar una Consulta",
    "consultation.subtitle": "Dé el primer paso para resolver su asunto legal. Complete el formulario a continuación y nuestro equipo revisará su caso.",
    "consultation.step1": "Detalles del Caso",
    "consultation.step2": "Información Personal",
    "consultation.step3": "Programación",
    "consultation.step1_title": "Cuéntenos Sobre Su Caso",
    "consultation.step2_title": "Su Información de Contacto",
    "consultation.step3_title": "Horario Preferido",
    "consultation.confidentiality": "Toda la información proporcionada es estrictamente confidencial y está protegida por el privilegio abogado-cliente.",
    "consultation.label.area": "Área de Práctica",
    "consultation.placeholder.area": "Seleccione un área de práctica",
    "consultation.option.other": "Otro Asunto Legal",
    "consultation.label.description": "Breve Descripción de Su Situación",
    "consultation.placeholder.description": "Por favor describa su problema legal, incluidas fechas importantes o plazos...",
    "consultation.label.urgency": "Nivel de Urgencia",
    "consultation.urgency.low": "Bajo - Planificando con anticipación",
    "consultation.urgency.medium": "Medio - Necesito consejo pronto",
    "consultation.urgency.high": "Alto - Se requiere acción inmediata",
    "consultation.button.next": "Siguiente Paso",
    "consultation.button.back": "Atrás",
    "consultation.button.submit": "Enviar Solicitud",
    "consultation.button.home": "Volver al Inicio",
    "consultation.label.firstname": "Nombre",
    "consultation.label.lastname": "Apellido",
    "consultation.label.email": "Dirección de Correo",
    "consultation.label.phone": "Número de Teléfono",
    "consultation.label.preferred_contact": "Método de Contacto Preferido",
    "consultation.option.email": "Correo Electrónico",
    "consultation.option.phone": "Llamada Telefónica",
    "consultation.summary.title": "Revise Su Información",
    "consultation.label.name": "Nombre",
    "consultation.label.contact": "Contacto",
    "consultation.label.time": "Hora Preferida del Día",
    "consultation.option.morning": "Mañana (9AM - 12PM)",
    "consultation.option.afternoon": "Tarde (12PM - 5PM)",
    "consultation.option.evening": "Noche (5PM - 7PM)",
    "consultation.consent": "Entiendo que enviar este formulario no crea una relación abogado-cliente hasta que se firme un acuerdo de honorarios.",
    "consultation.success.title": "Solicitud Recibida",
    "consultation.success.desc": "Gracias por contactar a Amaral Law. Nuestro equipo revisará su información y se comunicará con usted dentro de las 24 horas para confirmar su consulta.",

    // Detention Page
    "detention.title": "Guía de Respuesta a la Detención",
    "detention.subtitle": "Pasos inmediatos a seguir si un ser querido ha sido detenido por ICE.",
    "detention.step1.title": "Paso 1: Localice al Detenido",
    "detention.step1.desc": "Use el Localizador de Detenidos de ICE para encontrar dónde está detenido su ser querido. Necesitará su Número A y país de nacimiento, o su nombre completo y fecha de nacimiento.",
    "detention.step1.button": "Localizador de ICE",
    "detention.step2.title": "Paso 2: No Firme Nada",
    "detention.step2.desc": "Aconseje a su ser querido que NO firme ningún documento sin hablar con un abogado. Firmar una 'salida voluntaria' significa que aceptan ser deportados inmediatamente.",
    "detention.step3.title": "Paso 3: Contacte a un Abogado",
    "detention.step3.desc": "Llame a Amaral Law inmediatamente al 1-844-ICE-FREE. Podemos intervenir para detener el traslado, solicitar una audiencia de fianza y luchar por su liberación.",
    "detention.step3.button": "Llamar Ahora",
    "detention.rights.title": "Conozca Sus Derechos",
    "detention.rights.point1": "Tiene derecho a permanecer en silencio.",
    "detention.rights.point2": "Tiene derecho a hablar con un abogado.",
    "detention.rights.point3": "No tiene que firmar nada.",
    "detention.donts.title": "NO HACER",
    "detention.donts.point1": "Firmar documentos sin asesoramiento legal",
    "detention.donts.point2": "Prometer pagar una fianza que no puede pagar",
    "detention.donts.point3": "Discutir el caso con nadie excepto su abogado",
    "detention.donts.point4": "Faltar a las fechas de la corte",
    "detention.donts.point5": "Ignorar avisos oficiales",
    "detention.cta.title": "No Espere - Llame Ahora",
    "detention.cta.button": "Contáctenos Inmediatamente",
    
    // Action Bar
    "action_bar.title": "Acciones Inmediatas",
    "action_bar.ice_locator": "Localizar Detenido (ICE)",
    "action_bar.eoir_status": "Verificar Estado del Caso (EOIR)",

    // Consultation Scheduling
    "consultation.tab.inquiry": "Enviar Consulta",
    "consultation.tab.booking": "Reservar Cita",
    "consultation.booking.title": "Programe su Consulta",
    "consultation.booking.subtitle": "Seleccione un horario conveniente para hablar con nuestros abogados.",
    "consultation.fee.title": "Tarifa de Consulta: $250.00",
    "consultation.fee.desc": "Tenga en cuenta que hay una tarifa de consulta de $250.00 para todas las citas iniciales.",
    "consultation.fee.invoice": "Se le enviará una factura de LawPay por correo electrónico antes de su cita."
  },
  pt: {
    // Navigation
    "nav.home": "Início",
    "nav.attorneys": "Advogados",
    "nav.practice_areas": "Áreas de Atuação",
    "nav.knowledge_center": "Centro de Conhecimento",
    "nav.contact": "Contato",
    "nav.request_consultation": "Solicitar Consulta",
    
    // Hero
    "hero.call_now": "Ligue Agora",
    "hero.title_prefix": "Especialistas em",
    "hero.title_suffix": "Defesa de Remoção",
    "hero.description": "Quando você ou um ente querido enfrenta a detenção de imigração, o tempo é crítico. Nossos advogados experientes oferecem representação compassiva e agressiva para proteger seus direitos e garantir sua liberdade.",
    "hero.meet_attorneys": "Questionário de Fiança",
    
    // Footer
    "footer.tagline": "Fornecendo representação legal autorizada com compromisso com a justiça e integridade desde 1985.",
    "footer.practice_areas": "Áreas de Atuação",
    "footer.contact": "Contato",
    "footer.newsletter": "Boletim Informativo",
    "footer.subscribe_text": "Inscreva-se para receber insights jurídicos e atualizações do escritório.",
    "footer.email_placeholder": "Endereço de e-mail",
    "footer.join": "Juntar-se",
    "footer.rights": "Amaral Law Firm. Todos os direitos reservados.",
    "footer.privacy": "Política de Privacidade",
    "footer.terms": "Termos de Serviço",
    "footer.disclaimer": "Aviso Legal",
    "footer.accessibility": "Acessibilidade",
    "footer.admin": "Portal Administrativo",

    // Home Content
    "home.excellence_title": "Décadas de Excelência na Prática Jurídica",
    "home.excellence_p1": "Na Amaral Law, nos especializamos exclusivamente na defesa de imigrantes que enfrentam a deportação. Entendemos que sua vida nos Estados Unidos está em jogo e lutamos incansavelmente para manter as famílias unidas.",
    "home.excellence_p2": "Com um histórico comprovado no tribunal de imigração, nossos advogados defenderam com sucesso os direitos de inúmeras pessoas contra processos de remoção.",
    "home.learn_more": "Saiba Mais Sobre Nosso Escritório",
    "home.practice_areas_title": "Nossas Áreas de Atuação",
    "home.practice_areas_desc": "Focamos 100% na defesa de remoção. Nossa experiência especializada garante que você tenha o defensor mais forte possível no tribunal de imigração.",
    "home.latest_insights": "Últimos Insights Jurídicos",
    "home.view_all_articles": "Ver Todos os Artigos",

    // Practice Areas
    "practice.removal_defense": "Defesa de Remoção",
    "practice.removal_defense_desc": "Representação agressiva no tribunal de imigração para interromper processos de deportação.",
    "practice.asylum": "Asilo e Apelações",
    "practice.asylum_desc": "Tratamento especializado de pedidos de asilo e apelações BIA para casos complexos.",
    "practice.family": "Petições Familiares",
    "practice.family_desc": "Reunindo famílias através de ajuste de status e processamento consular.",
    "practice.bond": "Audiências de Fiança",
    "practice.bond_desc": "Lutando pela sua libertação dos centros de detenção de imigração.",
    "practice.crimmigration": "Crimigração",
    "practice.crimmigration_desc": "Defendendo não cidadãos que enfrentam acusações criminais que afetam o status de imigração.",
    "practice.federal": "Litígio Federal",
    "practice.federal_desc": "Desafiando pedidos atrasados ou negados no tribunal federal.",

    // Contact Page
    "contact.title": "Contate-nos",
    "contact.subtitle": "Entre em contato com nossa equipe jurídica para uma consulta.",
    "contact.form_title": "Envie-nos uma mensagem",
    "contact.name": "Nome Completo",
    "contact.email": "Endereço de E-mail",
    "contact.phone": "Número de Telefone",
    "contact.message": "Mensagem",
    "contact.submit": "Enviar Mensagem",
    "contact.info_title": "Informações de Contato",
    "contact.address": "Endereço",
    "contact.hours": "Horário de Funcionamento",
    "contact.hours_val": "Seg-Sex: 9:00 AM - 6:00 PM",

    // Bond Questionnaire
    "bond.title": "Questionário de Fiança",
    "bond.subtitle": "Por favor, preencha este formulário para nos ajudar a avaliar sua elegibilidade para uma fiança de imigração.",
    "bond.detainee_info": "Informações do Detento",
    "bond.full_name": "Nome Completo do Detento",
    "bond.a_number": "Número de Registro de Estrangeiro (A-Number)",
    "bond.dob": "Data de Nascimento",
    "bond.country_birth": "País de Nascimento",
    "bond.date_entry": "Data de Entrada nos EUA",
    "bond.manner_entry": "Forma de Entrada (ex: Visto, Fronteira)",
    "bond.detention_info": "Informações de Detenção",
    "bond.detention_center": "Centro de Detenção Atual",
    "bond.date_detained": "Data de Detenção",
    "bond.criminal_history": "Histórico Criminal (se houver)",
    "bond.family_ties": "Laços Familiares nos EUA",
    "bond.sponsor_info": "Informações do Patrocinador",
    "bond.sponsor_name": "Nome do Patrocinador",
    "bond.sponsor_relation": "Relação com o Detento",
    "bond.sponsor_status": "Status Imigratório do Patrocinador",
    "bond.sponsor_income": "Renda Anual",
    "bond.submit": "Enviar Questionário",

    // Vanity Number Section
    "vanity.title": "Memorize Este Número: 1-844-ICE-FREE",
    "vanity.subtitle": "Assistência Jurídica Imediata Quando Você Mais Precisa",
    "vanity.description": "No caso de uma detenção inesperada pelo ICE, cada segundo conta. Memorizar 1-844-ICE-FREE (1-844-262-5442) garante que você ou seus entes queridos possam se conectar instantaneamente com nossa equipe de defesa de remoção. Estamos disponíveis para fornecer orientação urgente e representação para lutar pela sua libertação.",
    "vanity.cta": "Salvar Contato Agora",

    // Attorneys Page
    "attorneys.title": "Nossa Equipe Jurídica",
    "attorneys.subtitle": "Advogados experientes dedicados ao seu caso",
    "attorneys.ana.role": "Advogada Principal de Imigração",
    "attorneys.ana.bio": "Imigrante do Brasil com mais de 40 anos nos EUA, Ana Paola é especialista em defesa de detenção e processos de remoção, trazendo experiência pessoal e profunda empatia para cada caso.",
    "attorneys.reggie.role": "Advogado de Litígio de Imigração Complexo",
    "attorneys.reggie.bio": "Especializado em litígios de imigração complexos com vasta experiência em processos de apelação, litígios em tribunais federais e casos de imigração desafiadores que exigem estratégias jurídicas avançadas.",
    "attorneys.balaiz.role": "Of Counsel - Litígio Civil",
    "attorneys.balaiz.bio": "Experiente em questões de litígio civil, incluindo disputas contratuais, reivindicações de propriedade e casos civis complexos. Fornece representação legal especializada para clientes que necessitam de aconselhamento especializado em direito civil.",
    "attorneys.values.title": "Nossos Valores",
    "attorneys.values.justice": "Justiça para Todos",
    "attorneys.values.justice_desc": "Acreditamos que toda pessoa merece representação legal de qualidade, independentemente de suas circunstâncias.",
    "attorneys.values.compassion": "Advocacia Compassiva",
    "attorneys.values.compassion_desc": "Tratamos cada cliente com dignidade, respeito e compreensão genuína de sua situação.",
    "attorneys.values.excellence": "Excelência Jurídica",
    "attorneys.values.excellence_desc": "Mantemos os mais altos padrões de prática jurídica e buscamos incansavelmente os melhores resultados.",
    "attorneys.values.community": "Compromisso Comunitário",
    "attorneys.values.community_desc": "Servimos ativamente as comunidades de imigrantes e defendemos uma reforma imigratória justa.",
    "attorneys.cta.title": "Não Enfrente a Detenção de Imigração Sozinho",
    "attorneys.cta.desc": "Cada dia na detenção importa. Contate-nos hoje para uma consulta gratuita e saiba como podemos ajudar a garantir sua libertação e lutar por seus direitos.",
    "attorneys.cta.button": "Solicitar Consulta Gratuita",

    // Knowledge Center
    "knowledge.title": "Centro de Conhecimento",
    "knowledge.subtitle": "Insights jurídicos especializados, guias detalhados e recursos práticos para ajudá-lo a navegar em cenários jurídicos complexos.",
    "knowledge.tab.guides": "Guias Jurídicos",
    "knowledge.tab.resources": "Recursos para Download",
    "knowledge.search": "Pesquisar tópicos...",
    "knowledge.read_article": "Ler Artigo",
    "knowledge.no_results": "Nenhum guia encontrado correspondente à sua pesquisa.",
    "knowledge.newsletter.title": "Mantenha-se Informado",
    "knowledge.newsletter.desc": "Inscreva-se em nosso boletim informativo mensal para receber os últimos insights jurídicos, notícias do escritório e atualizações regulatórias diretamente em sua caixa de entrada.",
    "knowledge.newsletter.placeholder": "Digite seu endereço de e-mail",
    "knowledge.newsletter.button": "Inscrever-se",
    "knowledge.newsletter.disclaimer": "Ao se inscrever, você concorda com nossa Política de Privacidade. Você pode cancelar a inscrição a qualquer momento.",
    
    // Guides
    "guide.1.title": "Responsabilidade Corporativa na Era Digital",
    "guide.1.desc": "Um guia abrangente para entender os novos riscos de responsabilidade para empresas digitais.",
    "guide.2.title": "Planejamento Sucessório para Proprietários de Empresas",
    "guide.2.desc": "Estratégias para proteger os ativos da sua empresa e garantir uma sucessão tranquila.",
    "guide.3.title": "Propriedade Intelectual: Patente vs. Segredo Comercial",
    "guide.3.desc": "Decidindo qual mecanismo de proteção é o certo para sua inovação.",
    "guide.4.title": "Navegando em Disputas de Locação Comercial",
    "guide.4.desc": "Passos principais a serem tomados ao enfrentar uma disputa com seu locador ou inquilino comercial.",
    "guide.5.title": "A Reforma Tributária de 2026: O Que Você Precisa Saber",
    "guide.5.desc": "Uma visão antecipada das mudanças propostas no código tributário e como se preparar.",
    "guide.6.title": "Direito de Família: Acordos Pré-nupciais Explicados",
    "guide.6.desc": "Dissipando mitos comuns sobre acordos pré-nupciais e entendendo seus benefícios.",
    
    // Resources
    "resource.1.title": "Lista de Verificação de Conformidade Corporativa 2025",
    "resource.2.title": "Questionário de Planejamento Sucessório",
    "resource.3.title": "Modelo de Auditoria de Propriedade Intelectual",
    "resource.4.title": "Glossário de Terminologia de Locação Comercial",

    // Home Insights
    "home.insight.1.title": "Entendendo Seus Direitos no Tribunal de Imigração",
    "home.insight.1.cat": "Defesa de Remoção",
    "home.insight.2.title": "Como Pagar Fiança para um Parente Detido",
    "home.insight.2.cat": "Detenção",
    "home.insight.3.title": "Mudanças na Elegibilidade de Asilo em 2024",
    "home.insight.3.cat": "Asilo",
    "home.insight.desc": "Leia nossa análise especializada sobre este tópico crítico que afeta empresas e indivíduos.",

    // Bond Questionnaire Extras
    "bond.description": "Por favor, forneça detalhes precisos sobre a pessoa atualmente detida.",
    "bond.placeholder.name": "ex: João Silva",
    "bond.placeholder.a_number": "A-123-456-789",
    "bond.placeholder.country": "ex: Brasil",
    "bond.placeholder.manner": "ex: Visto, Fronteira",
    "bond.placeholder.center": "ex: Centro de Detenção Krome",
    "bond.placeholder.criminal": "Por favor, liste quaisquer prisões ou condenações...",
    "bond.placeholder.family": "Liste os membros da família atualmente nos EUA (Relação e Status)",
    "bond.placeholder.sponsor_name": "ex: Maria Silva",
    "bond.placeholder.sponsor_relation": "ex: Esposa",
    "bond.placeholder.sponsor_status": "ex: Cidadã dos EUA, Portadora de Green Card",
    "bond.placeholder.sponsor_income": "ex: $45,000",

    // Consultation Extras
    "consultation.title": "Solicitar uma Consulta",
    "consultation.subtitle": "Dê o primeiro passo para resolver seu assunto jurídico. Preencha o formulário abaixo e nossa equipe analisará seu caso.",
    "consultation.step1": "Detalhes do Caso",
    "consultation.step2": "Informações Pessoais",
    "consultation.step3": "Agendamento",
    "consultation.step1_title": "Conte-nos Sobre Seu Caso",
    "consultation.step2_title": "Suas Informações de Contato",
    "consultation.step3_title": "Horário Preferido",
    "consultation.confidentiality": "Todas as informações fornecidas são estritamente confidenciais e protegidas pelo sigilo advogado-cliente.",
    "consultation.label.area": "Área de Atuação",
    "consultation.placeholder.area": "Selecione uma área de atuação",
    "consultation.option.other": "Outro Assunto Jurídico",
    "consultation.label.description": "Breve Descrição da Sua Situação",
    "consultation.placeholder.description": "Por favor, descreva seu problema jurídico, incluindo datas importantes ou prazos...",
    "consultation.label.urgency": "Nível de Urgência",
    "consultation.urgency.low": "Baixo - Planejando com antecedência",
    "consultation.urgency.medium": "Médio - Preciso de conselho em breve",
    "consultation.urgency.high": "Alto - Ação imediata necessária",
    "consultation.button.next": "Próximo Passo",
    "consultation.button.back": "Voltar",
    "consultation.button.submit": "Enviar Solicitação",
    "consultation.button.home": "Voltar ao Início",
    "consultation.label.firstname": "Nome",
    "consultation.label.lastname": "Sobrenome",
    "consultation.label.email": "Endereço de E-mail",
    "consultation.label.phone": "Número de Telefone",
    "consultation.label.preferred_contact": "Método de Contato Preferido",
    "consultation.option.email": "E-mail",
    "consultation.option.phone": "Chamada Telefônica",
    "consultation.summary.title": "Revise Suas Informações",
    "consultation.label.name": "Nome",
    "consultation.label.contact": "Contato",
    "consultation.label.time": "Horário Preferido do Dia",
    "consultation.option.morning": "Manhã (9h - 12h)",
    "consultation.option.afternoon": "Tarde (12h - 17h)",
    "consultation.option.evening": "Noite (17h - 19h)",
    "consultation.consent": "Entendo que o envio deste formulário não cria uma relação advogado-cliente até que um contrato de honorários seja assinado.",
    "consultation.success.title": "Solicitação Recebida",
    "consultation.success.desc": "Obrigado por entrar em contato com a Amaral Law. Nossa equipe analisará suas informações e entrará em contato com você dentro de 24 horas para confirmar sua consulta.",

    // Detention Page
    "detention.title": "Guia de Resposta à Detenção",
    "detention.subtitle": "Passos imediatos a serem tomados se um ente querido foi detido pelo ICE.",
    "detention.step1.title": "Passo 1: Localize o Detento",
    "detention.step1.desc": "Use o Localizador de Detentos do ICE para encontrar onde seu ente querido está detido. Você precisará do A-Number e país de nascimento, ou nome completo e data de nascimento.",
    "detention.step1.button": "Localizador do ICE",
    "detention.step2.title": "Passo 2: Não Assine Nada",
    "detention.step2.desc": "Aconselhe seu ente querido a NÃO assinar nenhum documento sem falar com um advogado. Assinar uma 'saída voluntária' significa que eles concordam em ser deportados imediatamente.",
    "detention.step3.title": "Passo 3: Contate um Advogado",
    "detention.step3.desc": "Ligue para a Amaral Law imediatamente em 1-844-ICE-FREE. Podemos intervir para impedir a transferência, solicitar uma audiência de fiança e lutar pela libertação.",
    "detention.step3.button": "Ligar Agora",
    "detention.rights.title": "Conheça Seus Direitos",
    "detention.rights.point1": "Você tem o direito de permanecer calado.",
    "detention.rights.point2": "Você tem o direito de falar com um advogado.",
    "detention.rights.point3": "Você não precisa assinar nada.",
    "detention.donts.title": "NÃO FAZER",
    "detention.donts.point1": "Assinar documentos sem aconselhamento jurídico",
    "detention.donts.point2": "Prometer pagar uma fiança que você não pode pagar",
    "detention.donts.point3": "Discutir o caso com ninguém, exceto seu advogado",
    "detention.donts.point4": "Faltar às datas do tribunal",
    "detention.donts.point5": "Ignorar avisos oficiais",
    "detention.cta.title": "Não Espere - Ligue Agora",
    "detention.cta.button": "Contate-nos Imediatamente",
    
    // Action Bar
    "action_bar.title": "Ações Imediatas",
    "action_bar.ice_locator": "Localizar Detento (ICE)",
    "action_bar.eoir_status": "Verificar Status do Caso (EOIR)",

    // Consultation Scheduling
    "consultation.tab.inquiry": "Enviar Consulta",
    "consultation.tab.booking": "Agendar Consulta",
    "consultation.booking.title": "Agende sua Consulta",
    "consultation.booking.subtitle": "Selecione um horário conveniente para falar com nossos advogados.",
    "consultation.fee.title": "Taxa de Consulta: $250.00",
    "consultation.fee.desc": "Observe que há uma taxa de consulta de $250.00 para todos os agendamentos iniciais.",
    "consultation.fee.invoice": "Uma fatura do LawPay será enviada para você por e-mail antes da sua consulta."
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
